### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by davidbrochart** [kylebarron/pydelatin#14]
I'm trying to make a conda-forge package (again :smile:) in https://github.com/conda-forge/staged-recipes/pull/12914.
It looks like you vendor hmm, and don't include the source files in the PyPI package. I guess for conda-forge we would first have to package hmm and have it as a dependency of pydelatin.
What do you think?

**Comment by kylebarron** [comment]
😄 Thanks for taking a stab at conda-forge here again, and apologies for my trouble in correctly packaging! Packaging is hard!

I'm still learning best practices for wrapping lower-level code (especially since I don't know C/C++ that well). In this package I actually expose _two_ libraries, the Pybind11 source is built from `src/` and is exposed as `_pydelatin`; then I have a separate wrapper in `pydelatin/` that's exposed as `pydelatin`. This helped since I couldn't really figure out how to pass 2D numpy arrays back from C++ directly.

Looking at the [0.2.0 source tarball](https://files.pythonhosted.org/packages/97/f9/71a506255b95f2c8b39c48ba243198562e1490cc5d8aeae6434dc867a064/pydelatin-0.2.0.tar.gz), it looks like the `src/` folder exists. So it seems like it _should_ work for building from source locally?

Separately, this does rely on one other external library: [`glm`](https://glm.g-truc.net/). It _should_ be easy to work with, since it's a header-only library. That said, I spent a couple hours last night [trying to get windows wheels to work](https://github.com/kylebarron/pydelatin/tree/windows-wheels), and just couldn't figure out how to correctly modify the include paths 😂 . So maybe you'd need to put `glm` on conda? I don't know

**Comment by davidbrochart** [comment]
So `glm` is on conda-forge: https://github.com/conda-forge/glm-feedstock
Maybe I was just missing that one. But anyway in conda-forge we shouldn't vendor another package, so I'm doing one for `hmm`.
Thanks for the information, I'll let you know how it goes!

**Comment by kylebarron** [comment]
Ok, it seems like I'd need to make changes to `pydelatin` to support an external `hmm`?

Like I'd probably need to change these includes
https://github.com/kylebarron/pydelatin/blob/c6f2a74175018e952efd26bf4a4506b400465567/src/main.cpp#L13-L15

to
```cpp
#include <hmm/base.h>
#include <hmm/heightmap.h>
#include <hmm/triangulator.h>
```

The `main.cpp` is the only C++ file I modified directly. Since I'm a total noob to good building practices, I might be wary of making changes unless it's clear how to also change the wheel building process. Like I know I should be able to fetch `hmm` and `glm` from github, and link against them in `main.cpp` without hardcoding anything, but I need to research how to do that

**Comment by davidbrochart** [comment]
OK I'm done with hmm: https://github.com/conda-forge/staged-recipes/pull/12915
Would you like to be a maintainer of the conda-forge package?

**Comment by kylebarron** [comment]
Sure

**Comment by davidbrochart** [comment]
You know more than me about pip packaging, but what are the options to not vendor another library (here `hmm` and `glm`)? Can you download e.g. `https://github.com/fogleman/hmm/archive/v1.1.0.tar.gz`?
In any case, yes you will need to change to:
```cpp
#include "hmm/base.h"
#include "hmm/heightmap.h"
#include "hmm/triangulator.h"
```

**Comment by davidbrochart** [comment]
Maybe it's fine for now, we can see if we can improve that in the future.

**Comment by davidbrochart** [comment]
We now have a conda-forge package: https://github.com/conda-forge/pydelatin-feedstock
To install it:
```bash
$ conda install pydelatin -c conda-forge
```
Thanks again for this great library!
